{% set name = "opentelemetry-proto" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-proto-{{ version }}.tar.gz
  sha256: 6dc2290ee65ea491343b7b42faddc1d10b74ae086c08506a4c85779edc25dc8a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - protobuf >=3.13.0
    - python >=3.6

test:
  imports:
    - opentelemetry
    - opentelemetry.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-proto
  summary: OpenTelemetry Python Proto
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
