{% set name = "opentelemetry-proto" %}
{% set version = "1.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-telemetry/{{ name.split('-')[0] }}-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c7e941a92e52dc876d60177a81d4d44951a06a70f324a5ccfd956a18725885b9

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install ./{{ name }} -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - protobuf >=5.0,<7.0

test:
  source_files:
    - {{ name }}/tests
  imports:
    - opentelemetry
    - opentelemetry.proto
    - opentelemetry.proto.collector
    - opentelemetry.proto.common
    - opentelemetry.proto.logs
    - opentelemetry.proto.metrics
    - opentelemetry.proto.profiles
    - opentelemetry.proto.resource
    - opentelemetry.proto.trace
  commands:
    - pip check
    - pytest -v {{ name }}/tests
  requires:
    - pip
    - pytest >=7.4.4
    - colorama >=0.4.6
    - iniconfig >=2.0.0
    - packaging >=24.0

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-proto
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: OpenTelemetry Python / Proto
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.
  doc_url: https://opentelemetry-python.readthedocs.io
  dev_url: https://github.com/open-telemetry/opentelemetry-python

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - mariusvniekerk
