{% set name = "opentelemetry-proto" %}
{% set version = "1.12.0" %}
{% set sha256 = "c7f3f2dab9060769ac3ca67b147a0433d7326d5622eed6ef8039afebd80591e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-proto-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # noarch: python
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - protobuf >=3.13,<4
    - python

test:
  imports:
    - opentelemetry
    - opentelemetry.proto
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Python / Proto
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-proto
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io/en/latest/
  doc_source_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/docs
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.

extra:
  recipe-maintainers:
    - mariusvniekerk
